name: Update CKEditor 5 blob

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                registry-url: 'https://npm.pkg.github.com'
                scope: '@ftrprf'
            - name: build editor
              run: cd ./packages/ckeditor5-build-decoupled-document && npm install && npm run build
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_REPO_TOKEN }}
            - name: upload to storage
              env:
                  AZURE_STORAGE_ACCOUNT: "ckeditorbuild"
                  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
              run: az storage blob upload-batch -s ./packages/ckeditor5-build-decoupled-document/build/ckeditor.js -d \ckeditor5.js --overwrite
